# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'localReminders' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for localReminders
  pod 'Firebase/Core', '~> 6.2.0'
  pod 'Firebase/Messaging', '~> 6.2.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
